//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSchedule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLesson
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdLesson { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Lesson Lesson { get; set; }
    }
}
